In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv("/kaggle/input/bank-churn-data/bank_churn_data.csv")

In [3]:
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1  15634602.0  Hargrave          619    France  Female   42   
1          2  15647311.0      Hill          608     Spain  Female   41   
2          3  15619304.0      Onio          502    France  Female   42   
3          4  15701354.0      Boni          699    France  Female   39   
4          5  15737888.0  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     2.0       0.00            1.0          1               1   
1     1.0   83807.86            1.0          0               1   
2     8.0  159660.80            3.0          1               0   
3     1.0       0.00            2.0          0               0   
4     2.0  125510.82            1.0          1               1   

   EstimatedSalary  Exited  
0        101348.88     1.0  
1        112542.58     0.0  
2        113931.57     1.0  
3         93826.63     0.0  
4         79084.10     0.0

In [4]:
ds.sample(10)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
7506       7507  15700300.0      Okoli          674   Germany  Female   44   
5464       5465  15795540.0       Reye          556    France  Female   36   
9266       9267  15682273.0      Burns          683    France  Female   38   
7959       7960  15686999.0   Nicholas          556    France  Female   40   
9433       9434  15582903.0    Edwards          643    France    Male   39   
7501       7502  15605341.0      Baird          681    France  Female   58   
5516       5517  15569878.0       Dale          592    France    Male   37   
1177       1178  15651369.0     Wright          626    France    Male   21   
8389       8390  15715345.0  Sergeyeva          743     Spain    Male   25   
106         107  15599195.0     Stiger          582   Germany    Male   32   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
7506     4.0  131593.85            1.0          0               1   
5464     2.0  134208.22            1.0          0               1   
9266     5.0  127616.56            1.0          1               0   
7959     8.0       0.00            2.0          1               0   
9433     7.0       0.00            2.0          1               1   
7501     8.0   93173.88            1.0          1               1   
5516     3.0   96651.03            1.0          1               1   
1177     1.0       0.00            2.0          1               0   
8389     6.0       0.00            2.0          1               0   
106      1.0   88938.62            1.0          1               1   

      EstimatedSalary  Exited  
7506        171345.02     1.0  
5464        177670.57     0.0  
9266        123846.07     0.0  
7959         62112.70     0.0  
9433        170392.59     0.0  
7501        139761.25     0.0  
5516          3232.82     0.0  
1177         66232.23     0.0  
8389        129740.11     0.0  
106          10054.53     0.0

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       9999 non-null   float64
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        9999 non-null   object 
 5   Gender           9998 non-null   object 
 6   Age              10000 non-null  int64  
 7   Tenure           9999 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    9998 non-null   float64
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB


In [6]:
ds.isnull().sum()

RowNumber          0
CustomerId         1
Surname            0
CreditScore        0
Geography          1
Gender             2
Age                0
Tenure             1
Balance            0
NumOfProducts      2
HasCrCard          0
IsActiveMember     0
EstimatedSalary    1
Exited             1
dtype: int64

In [7]:
ds.shape

(10000, 14)

In [8]:
ds.dropna(inplace=True)

In [9]:
ds.shape

(9993, 14)

In [10]:
ds.columns


Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [11]:
ds.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [12]:
ds.drop(['RowNumber', 'CustomerId', 'Surname', 'Gender'], axis='columns',inplace=True)


In [13]:
x=ds[['CreditScore','Geography','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']].values

In [14]:
y=ds[['Exited']].values

In [15]:
x

array([[619, 'France', 42, ..., 1, 1, 101348.88],
       [608, 'Spain', 41, ..., 0, 1, 112542.58],
       [502, 'France', 42, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 36, ..., 0, 1, 42085.58],
       [772, 'Germany', 42, ..., 1, 0, 92888.52],
       [792, 'France', 28, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
y

array([[1.],
       [0.],
       [1.],
       ...,
       [1.],
       [1.],
       [0.]])

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
label=LabelEncoder()
x[:,1]=label.fit_transform(x[:,1])

In [19]:
x

array([[619, 0, 42, ..., 1, 1, 101348.88],
       [608, 2, 41, ..., 0, 1, 112542.58],
       [502, 0, 42, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 36, ..., 0, 1, 42085.58],
       [772, 1, 42, ..., 1, 0, 92888.52],
       [792, 0, 28, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [22]:
x_train

array([[790, 1, 25, ..., 1, 0, 58214.79],
       [800, 1, 39, ..., 1, 0, 13906.34],
       [756, 0, 28, ..., 1, 1, 164394.65],
       ...,
       [795, 0, 36, ..., 1, 1, 135388.89],
       [709, 0, 39, ..., 1, 0, 56214.09],
       [637, 0, 38, ..., 0, 0, 119882.86]], dtype=object)

In [23]:
x_test

array([[614, 0, 41, ..., 1, 1, 598.8],
       [518, 0, 38, ..., 0, 1, 162304.59],
       [547, 1, 55, ..., 1, 0, 16922.28],
       ...,
       [647, 0, 33, ..., 1, 0, 152323.04],
       [589, 0, 31, ..., 1, 0, 148218.86],
       [704, 0, 40, ..., 0, 1, 179964.55]], dtype=object)

In [24]:
y_train

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [25]:
y_test

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [26]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
model.predict(x_test)

array([0., 1., 1., ..., 0., 0., 0.])

In [28]:
y_test

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [29]:
model.score(x_test,y_test)

0.7738492328218812